-- MySQL Workbench Synchronization
-- Generated: 2024-12-05 20:08
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Felipe

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `pews` DEFAULT CHARACTER SET utf8mb3 ;

CREATE TABLE IF NOT EXISTS `pews`.`enfermeira` (
  `cip` INT(11) NOT NULL,
  `nome_enfermeira` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS `pews`.`medico` (
  `crm` INT(11) NOT NULL,
  `area` VARCHAR(255) NOT NULL,
  `nome_medico` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`crm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS `pews`.`paciente` (
  `idpaciente` INT(11) NOT NULL,
  `nome_paciente` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS `pews`.`tecnico_enfermagem` (
  `identificador` INT(11) NOT NULL,
  `nome_tecnico` VARCHAR(45) NOT NULL,
  `area_tecnico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identificador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
